### ISSUE TITLE
Split PKGBUILD

### ISSUE THREAD

**Issue by demmm** [KaOS-Community-Packages/gvfs#1]
Is it actually tested that this split PKGBUILD fully functions?  KCP does not support splits....

**Comment by Gabrielgtx** [comment]
if I have tested and everything works fine. we should incorporate
guidelines PKGBUILD divided to reduce dependencies into kcp

2016-02-08 10:07 GMT-04:30 demmm <notifications@github.com>:

**Comment by demmm** [comment]
Bigger question is why you did a split PKGBUILD.  Even that it builds does not make it work in KCP, only one package of all you split here shows in searches/stream/description.
Exactly why is it need to split?  If nothing needs the other parts, why add?  If the other parts are useful, why not ship as upstream intended?

**Comment by demmm** [comment]
Plus I'll keep it in one issue, one on earth do you have a group "gnome"?

As is now, this package has no place in KCP, will be removed within 24 hours.  See http://kaosx.us/phpBB3/viewtopic.php?f=12&t=1339

**Comment by Gabrielgtx** [comment]
I have no gnome group, I went up that package at the request of a member of the group Kaos telegram. I'm finally erasing that is necessary to keep it for use by one person
